---
title: "chapter3 0318"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



## packages

```{r}
library(googlesheets4)

```

```{r}
library(readr)
exDataPost80s <- read_csv("https://www.dropbox.com/s/rc6t40gsxduysz6/exDataPost80s.csv?dl=1")
View(exDataPost80s)

```

```{r}
library(readr)
hypothesisData <- read_csv("https://www.dropbox.com/s/0etoflih5eqc0bc/hypothesisData.csv?dl=1")
View(hypothesisData)

```

## Create objects

```{r}
a <- 2
a = 2 # = 與 <-同義
```

```{r}
3 -> b
```

```{r}
a+b
```

```{r}
my_108_total_credits <- 15
_108_total_credits <- 15
108_total_credits <- 15
_my_108_total_credits <- 15
my.108.total_credits <- 15
.108.total_credits <- 15 # 隱藏變數(用點開始不會出現在environment)
.my.108.total_credits <- 15
我的108學年總學分數 <- 15
`我的108學年總學分數` <- 15 # 特殊名稱處理，`不是名稱的一部份
`.108.total_credits` <- 15
```


## calling an object

```{r}
`我的年紀` <- 20
my_age <- `我的年紀`
```

## Atomic vector

## Numeric

```{r}
num1 <- 5
vNum1 <- c(2,5)
vNum2 <- c(2, num1)
```

```{r}
vNum1 <- c(-1,5)
vNum2 <- c(2,3)
vNum3 <- c(vNum1,vNum2)
vNum4 <- c(-1,5,2,3)
vNum5 <- c(c(-1,5),c(2,3))
```

Exercise
```{r}
vNum1 <- c(-1,5)
vNum2 <- c(2,3)
vNum4 <- c() # 空向量
```

```{r}
vNum3 <- c(vNum2, vNum1)
vNum4 <- c(vNum4, vNum1) # 向量疊代 （recursive vector concatenate）
```

```{r}
library(httr)
library(dplyr)
GET("https://github.com/niki45669/108-2-78-inclass-practice") %>%
  content() %>%
  View()
```



### Logi

```{r}
logi1 <- c(T,TRUE,F,FALSE,FALSE)
```

```{r}
# 加總向量內的所有元素值。
sum(logi1)
```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
